#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 19 14:22:23 2021

@author: sujwary
"""
import signatureanalyzer as sa
import pandas as pd

# ---------------------
# RUN SIGNATURE ANALYZER
# ---------------------

celltype = 'NK_RemoveRiboFeatures'
path = "/home/sujwary/Desktop/scRNA/Data/NMF/Harmony_AllSamples_Sample_Kit_" + celltype
input_matrix = pd.read_csv(path + ".tsv", sep='\t')

sa.run_matrix(matrix=input_matrix, outdir= path + '_phi1_alpha10_test/', 
              nruns=100,verbose=True,plot_results=False,K0=20,tolerance=1e-6,
              objective='gaussian', max_iter=30000, phi=1.0, a=10.0)
 
